source("new/global.R", local = TRUE, encoding = "UTF-8")
source("new/ui.R", local = TRUE, encoding = "UTF-8")

ui_markup <- as.character(ui)
ui_source <- paste(readLines("new/ui.R", warn = FALSE, encoding = "UTF-8"), collapse = "\n")

stopifnot(grepl("RiboTE", ui_markup, fixed = TRUE))
stopifnot(grepl("Load Data", ui_markup, fixed = TRUE))
stopifnot(grepl("Data Preprocess", ui_markup, fixed = TRUE))
stopifnot(grepl("Translation Efficiency", ui_markup, fixed = TRUE))
stopifnot(grepl("PCA", ui_markup, fixed = TRUE))
stopifnot(grepl("Clustering", ui_markup, fixed = TRUE))
stopifnot(grepl("GSEA", ui_markup, fixed = TRUE))
stopifnot(grepl("Enrichment", ui_markup, fixed = TRUE))
stopifnot(grepl("Network", ui_markup, fixed = TRUE))
stopifnot(grepl("SignalP", ui_markup, fixed = TRUE))
stopifnot(grepl("Codon", ui_markup, fixed = TRUE))
stopifnot(grepl("RiboTE | Rice Research Institute, Guangdong Academy of Agricultural Sciences | Guangzhou, Guangdong, China | 2026", ui_markup, fixed = TRUE))
stopifnot(!grepl("RNAmeta", ui_markup, fixed = TRUE))
stopifnot(!grepl("Module Entry", ui_markup, fixed = TRUE))
stopifnot(!grepl("Species and matrix context", ui_markup, fixed = TRUE))
stopifnot(!grepl("navbarMenu\\(\\s*\"Preprocess\"", ui_source))
stopifnot(!grepl("navbarMenu\\(\\s*\"TE Analysis\"", ui_source))
stopifnot(!grepl("navbarMenu\\(\\s*\"Functional\"", ui_source))

cat("ribote shell ui test passed\n")
