ProxyPreserveHost On
ProxyRequests Off

RequestHeader set X-Forwarded-Proto "https"

RedirectMatch 302 ^/RiboTE$ /RiboTE/

ProxyPass        /RiboTE/websocket/   ws://127.0.0.1:10802/websocket/
ProxyPassReverse /RiboTE/websocket/   ws://127.0.0.1:10802/websocket/

ProxyPass        /RiboTE/autoreload/  ws://127.0.0.1:10802/autoreload/
ProxyPassReverse /RiboTE/autoreload/  ws://127.0.0.1:10802/autoreload/

ProxyPass        /RiboTE/session/     http://127.0.0.1:10802/session/
ProxyPassReverse /RiboTE/session/     http://127.0.0.1:10802/session/

ProxyPass        /RiboTE/react/app_shell/  http://127.0.0.1:10802/react/app_shell/
ProxyPassReverse /RiboTE/react/app_shell/  http://127.0.0.1:10802/react/app_shell/

ProxyPass        /RiboTE/css/         http://127.0.0.1:10802/css/
ProxyPassReverse /RiboTE/css/         http://127.0.0.1:10802/css/

ProxyPass        /ribote-resources/   http://127.0.0.1:10802/ribote-resources/
ProxyPassReverse /ribote-resources/   http://127.0.0.1:10802/ribote-resources/

ProxyPass        /RiboTE/             http://127.0.0.1:10802/
ProxyPassReverse /RiboTE/             http://127.0.0.1:10802/
